<?xml version="1.0" encoding="iso-8859-1" ?>
<!DOCTYPE ws:source SYSTEM "websource.dtd">
<ws:source name="apec.fr" xmlns:ws="http://wwwsource.free.fr/ns/websource">
  <ws:fetch name="init" forward-to="init-parser">
    <data>http://cadres.apec.fr/Accueil/ApecIndexAccueil.jsp</data>
  </ws:fetch>

  <ws:xmlparser name="init-parser" forward-to="link" />

  <ws:extract name="link" forward-to="fetcher">
    <path>//a[contains(.,"offres d'emploi cadres")]/@href</path>
  </ws:extract>

  <ws:fetch name="fetcher" forward-to="parser" />

<!--   <ws:cache name="cache" forward-to="parser"
            directory="/tmp" template="apec-init-XXXXX.html" />
 -->
  <ws:xmlparser name="parser" forward-to="select next" />

  <ws:extract name="next" forward-to="fetcher">
    <path>//a[contains(.,"Suivante")]/@href</path>
  </ws:extract>

  <ws:extract name="select" forward-to="format">
    <path>//div[contains(@class,"offre")]</path>
  </ws:extract>

  <ws:extract type="xslt" name="format" forward-to="map"
              xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
    <xsl:stylesheet version="1.0">
      <xsl:output method="xml" indent="yes" />
      <xsl:template match="div">
        <oml:object
          xmlns:oml="http://objectml.org/ns/200905/ObjectML"
          xmlns:cat="http://objectml.org/ns/200905/Categories"
          oml:datasource="http://www.apec.fr/"
          oml:category="cat:jobs">
            <xsl:attribute name="oml:id">
            	<xsl:value-of select=".//a/@href" />
            </xsl:attribute>
            <xsl:attribute name="oml:name">
            	<xsl:value-of select="normalize-space(.//a)" />
            </xsl:attribute>
            <xsl:copy-of select="." />
         </oml:object>
      </xsl:template>
    </xsl:stylesheet>
  </ws:extract>

  <ws:map name="map" forward-to="db">
    <map-to name="id" select="/oml:object/@oml:id" />
    <map-to name="name" select="/oml:object/@oml:name" />
    <map-to mode="xml" name="content" select="/oml:object/node()" />
  </ws:map>

  <ws:database name="db" forward-to="out">
    <parameters>
      <param name="db" value="objectml_store" />
      <param name="user" value="objectml" />
      <param name="pass" value="objectml" />
    </parameters>
    <query>
      INSERT INTO oml_object(uri,name,category,datasource,description)
      (SELECT concat('http://www.apec.fr/','$id'), '$name', cat.id, ds.id, '$content'
      FROM oml_category cat, oml_datasource ds
      WHERE cat.namespace = 'http://objectml.org/ns/200905/Category'
        AND cat.name = 'jobs'
        AND ds.uri = 'http://www.apec.fr/')
    </query>
  </ws:database>

  <ws:format name="out" format="xml" />
</ws:source>
