<?xml version="1.0" encoding="iso-8859-1" ?>
<!DOCTYPE ws:source SYSTEM "websource.dtd">
<ws:source name="Google.fr" xmlns:ws="http://wwwsource.free.fr/ns/websource">

  <ws:query name="q" method="GET" forward-to="fetcher">
    <base>http://www.google.fr/search</base>
    <parameters>
      <param name="q" value-of="data"/>
      <param name="hl" default="en" />
      <param name="lr" default="en" />
      <param name="ie" default="UTF-8" />
      <param name="oe" default="UTF-8" />
      <param name="spell" default="0" />
    </parameters>
  </ws:query>
  
  <ws:fetch name="fetcher" type="xml" forward-to="links next"/>

  <ws:extract name="next" forward-to="fetcher" method="xpath">
    <path>/descendant::a[./child::img[@src="/nav_next.gif"]]/@href</path>
  </ws:extract>

  <ws:extract name="links" method="xpath">
    <path>//p[@class="g" and contains(span/font/b,"PDF")]/a[1]/@href</path>
  </ws:extract>
</ws:source>
